name:                ghc-qualified-do-plugin
version:             0.1.0.0
github:              "githubuser/ghc-qualified-do-plugin"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ghc-qualified-do-plugin#readme>

ghc-options:
- -Wall
dependencies:
- base >= 4.7 && < 5
- ghc-lib-parser-ex

library:
  source-dirs: src
  dependencies:
  - ghc
  when:
    - condition: "impl(ghc < 9)"
      dependencies: syb

executables:
  ghc-qualified-do-plugin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-qualified-do-plugin

tests:
  ghc-qualified-do-plugin-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ghc-qualified-do-plugin
